class Devbench < Formula
  include Language::Python::Virtualenv

  desc "ConfigForge: 11-format config converter with comment preservation"
  homepage "https://naxiai.com/tools/devbench/"
  url "https://files.pythonhosted.org/packages/source/d/devbench/devbench-1.0.0.tar.gz"
  sha256 "31adca225a8994f14cc29468ba91a9cfc324860c0b4810bc64d5f4dd5a122fb8"
  license "MIT"
  head "https://github.com/apeters247/devbench.git", branch: "main"

  bottle do
    # Bottles are generated by CI — leave empty until first release
  end

  depends_on "python@3.12"

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5763e3b5a14/PyYAML-6.0.1.tar.gz"
    sha256 "bfdf460b1736c775f2ba9f6a92bca30bc2095067b8a9d77876d1fad6cc3b4a43"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devbench --version")
    assert_match "configforge", shell_output("#{bin}/devbench --list 2>&1")

    # Smoke test: JSON to YAML conversion
    (testpath/"test.json").write('{"host": "localhost", "port": 5432}')
    result = shell_output("#{bin}/devbench cf -f json -t yaml #{testpath}/test.json")
    assert_match "host:", result
    assert_match "localhost", result
  end
end
