#!/usr/bin/env python3
"""Try multiple Gemini models for a query, fall back through the list."""
import json, urllib.request, sys
from pathlib import Path

key = ''
for env_path in [Path('/var/www/herbalist/.env'), Path('/var/www/devbench/.env')]:
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if 'GOOGLE_API_KEY' in line and not line.startswith('#'):
                parts = line.split('=', 1)
                if len(parts) > 1:
                    key = parts[1].strip().strip('"\'')
                    if key: break
        if key: break

prompt = sys.argv[1]
outfile = sys.argv[2]
models = sys.argv[3:] if len(sys.argv) > 3 else ['gemini-3.5-flash', 'gemini-3-flash-preview', 'gemini-2.5-flash', 'gemini-2.0-flash']

print(f"Prompt ({len(prompt)} chars) -> {outfile}", file=sys.stderr)

for model in models:
    url = 'https://generativelanguage.googleapis.com/v1beta/models/' + model + ':generateContent?key=' + key
    body = json.dumps({'contents': [{'parts': [{'text': prompt}]}], 'generationConfig': {'maxOutputTokens': 8192}}).encode()
    req = urllib.request.Request(url, data=body, headers={'Content-Type': 'application/json'})
    try:
        resp = urllib.request.urlopen(req, timeout=30)
        data = json.loads(resp.read())
        result = data['candidates'][0]['content']['parts'][0]['text']
        with open(outfile, 'w') as f:
            f.write(result)
            f.write('\n\n---\n_Generated by: ' + model + '_\n')
        print(f'SUCCESS with {model}', file=sys.stderr)
        sys.exit(0)
    except urllib.error.HTTPError as e:
        err = e.read().decode()
        if e.code == 429:
            print(f'429 on {model}, trying next...', file=sys.stderr)
            continue
        print(f'{e.code} on {model}: {err[:200]}', file=sys.stderr)
        continue
    except Exception as e:
        print(f'Error on {model}: {e}', file=sys.stderr)
        continue

print('ALL MODELS FAILED', file=sys.stderr)
sys.exit(1)